/*
 * This source file was generated by the Gradle 'init' task
 */
package org.notepad.utilities;

class Utils {
  public Utils() {
  }

  public static String readFile(String path) {
    return "";
  }
}
