/*
 * This source file was generated by the Gradle 'init' task
 */
package org.notepad.app;

import java.net.URL;

import org.notepad.app.controllers.AppController;

// import static org.notepad.app.MessageUtils.getMessage;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) {

        try {
            URL fxmlUrl = getClass().getResource("/main.fxml");

            FXMLLoader loader = new FXMLLoader(fxmlUrl);

            Parent root = loader.load();

            AppController controller = loader.getController();
            controller.setPrimaryStage(primaryStage);

            primaryStage.setTitle("Notepad App");
            primaryStage.setScene(new Scene(root, 800, 600));

            // Handle window close request
            primaryStage.setOnCloseRequest(event -> {
                if (!controller.confirmExit()) {
                    event.consume();
                }
            });

            primaryStage.show();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error loading FXML: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
